# Generated by Django 4.2.3 on 2023-09-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=11),
            preserve_default=False,
        ),
    ]
